import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import{Search,Play,CheckCircle2,XCircle,Clock3,Workflow,AlertTriangle,Sparkles}from'lucide-react';import'./styles.css';

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

function App(){
 const[q,setQ]=useState('');const[loading,setLoading]=useState(false);const[matches,setMatches]=useState([]);const[error,setError]=useState('');const[selected,setSelected]=useState(null);const[runs,setRuns]=useState([]);
 const stats=useMemo(()=>({library:'1,970',ready:matches.length,status:'Online'}),[matches]);
 async function find(){if(!q.trim())return;setLoading(true);setError('');setMatches([]);setSelected(null);try{const{data,error}=await supabase.rpc('jarvis_match',{q:q.trim(),limit_count:3});if(error)throw error;setMatches(data||[]);if(data?.[0])setSelected(data[0]);}catch(e){setError(e.message||'Could not search workflows.');}finally{setLoading(false)}}
 function fakeRun(){if(!selected)return;const item={id:Date.now(),name:selected.name,status:'waiting',attempt:1,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})};setRuns(r=>[item,...r]);}
 return <div className="app"><aside><div className="brand"><div className="logo">J</div><div><b>JARVIS</b><span>Automation Control</span></div></div><nav><button className="active"><Sparkles size={18}/>Find Automation</button><button><Workflow size={18}/>Runs</button><button><AlertTriangle size={18}/>Failures</button></nav><div className="asideFooter"><span className="dot"></span>System online</div></aside>
 <main><header><div><p className="eyebrow">CONTROL CENTER</p><h1>What do you want automated?</h1><p className="sub">Describe the job in plain English. Jarvis finds the best workflow for you.</p></div><div className="statusPill"><span></span>Ready</div></header>
 <section className="heroCard"><div className="searchBox"><Search size={22}/><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Example: When a Stripe payment arrives, send the customer details to Slack..." onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')find()}}/></div><div className="searchFooter"><span>Ctrl + Enter to search</span><button onClick={find} disabled={loading||!q.trim()}>{loading?'Searching...':'Find best workflow'}</button></div></section>
 <section className="stats"><div><span>Workflow library</span><b>{stats.library}</b><small>active unique workflows</small></div><div><span>Matches found</span><b>{stats.ready}</b><small>top ranked results</small></div><div><span>Jarvis status</span><b className="green">{stats.status}</b><small>US East</small></div></section>
 {error&&<div className="error"><XCircle size={18}/>{error}</div>}
 {matches.length>0&&<section><div className="sectionTitle"><div><p className="eyebrow">BEST MATCHES</p><h2>Pick one and run it</h2></div></div><div className="matchGrid">{matches.map((m,i)=><article key={m.id} onClick={()=>setSelected(m)} className={selected?.id===m.id?'selected':''}><div className="rank">#{i+1}</div><div className="matchHead"><div><h3>{m.name}</h3><p>{m.reason||'Strong workflow match'}</p></div>{i===0&&<span className="best">BEST MATCH</span>}</div><div className="chips">{(m.integrations||[]).slice(0,5).map(x=><span key={x}>{x}</span>)}{m.trigger_type&&<span>{m.trigger_type}</span>}</div><div className="score"><span>Match score</span><b>{Math.round((m.score||0)*10)/10}</b></div></article>)}</div>
 <div className="runBar"><div><p>Selected workflow</p><b>{selected?.name||'Choose a workflow'}</b></div><button onClick={fakeRun} disabled={!selected}><Play size={20} fill="currentColor"/>RUN TEST</button></div></section>}
 <section className="runs"><div className="sectionTitle"><div><p className="eyebrow">TEST RUNS</p><h2>Latest activity</h2></div></div>{runs.length===0?<div className="empty"><Clock3 size={26}/><div><b>No test runs yet</b><p>Choose a workflow above and press RUN TEST.</p></div></div>:runs.map(r=><div className="runRow" key={r.id}><div className="runIcon"><Clock3 size={18}/></div><div className="runName"><b>{r.name}</b><span>Attempt {r.attempt} · {r.time}</span></div><span className="waiting">Waiting for n8n connection</span></div>)}</section>
 <section className="failureBox"><div><AlertTriangle size={22}/><div><b>Failures needing you</b><p>Anything that still fails after 3 attempts will appear here.</p></div></div><span>0</span></section>
 </main></div>}
createRoot(document.getElementById('root')).render(<App/>);
